// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reset.sql

package database

import (
	"context"
)

const resetu = `-- name: Resetu :exec
DELETE FROM users
`

func (q *Queries) Resetu(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetu)
	return err
}
